### ISSUE TITLE
324 - Assess site performance bottlenecks

### ISSUE THREAD

**Issue by treasuretron** [spacebase/spacebasenz#330]
In GitLab by @thomasmurphy on Feb 25, 2019, 22:11

* Look at the font modules to see if they are slowing us down.
* Analyse PHP processes to document high resource consumers, eg errors, uncached views etc
* Assess caching of front page map views. They are currently set to tags based caching, but we don't know what this is in practice and if it helps much.
* Work out a way of having different config on master, eg not to propagate config which disables core drupal caching to production, which has happened a few times.

**Comment by treasuretron** [comment]
In GitLab by @thomasmurphy on Feb 25, 2019, 22:11

changed title from **Assess site performance bottlenecks** to **{+324 - +}Assess site performance bottlenecks**

**Comment by treasuretron** [comment]
In GitLab by @thomasmurphy on Feb 25, 2019, 22:11

assigned to @jayelless

**Comment by treasuretron** [comment]
In GitLab by @jayelless on Feb 27, 2019, 18:15

Views caching is set to tag based, which means that if any of the details of a tagged entity changes, then the cache should be invalidated.  The contexts and tags specified for the front page map are (from the detail in the file views.view.organizations_nz_overview_map.yml):
```
    cache_metadata:
      max-age: -1
      contexts:
        - 'languages:language_content'
        - 'languages:language_interface'
        - url
        - user
      tags:
        - 'config:core.entity_view_display.group.organization_group.default'
        - 'config:core.entity_view_display.group.organization_group.map_display'
        - 'config:core.entity_view_display.group.organization_group.search_result'
        - 'config:field.storage.group.field_map_address'
        - 'config:field.storage.group.field_website'
```

This indicates that the view cache depends (among other things) on the user viewing it, and details of any included organization (which is ALL of them).  Each user will have a separately cached copy, and if any organization details are updated, then all cached copies of this view will be invalidated, and will need to be rebuilt.

Use of the contrib module "Views Custom Cache Tags" (https://www.drupal.org/project/views_custom_cache_tag) may allow better control of the cache contexts and tags to improve the cachability of custom views.  There is also another similar module "Views Advanced Cache (https://www.drupal.org/project/views_advanced_cache) that possibly allows better control, but this is not yet available in a production release nor is it used in many sites.
